# Spring Configuration
spring:
  application:
    name: Wallet Crypto
  main:
    web-application-type: reactive
  cloud:
    vault:
      host:
      port:
      authentication:
      token:
      scheme:
      kv:
        enabled: true
    azure:
      keyvault:
        secret:
          endpoint:
      appconfiguration:
        endpoint:

# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.blockchainconnector: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Application Configuration
app:
  secretProvider:
    name:

# Application Configuration
openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    description:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:

# Wallet Configuration
wallet-data:
  url:
