## Spring Configuration
#spring:
#  application:
#    name: wallet-crypto
#
## Server Configuration
#server:
#  port: 8081
#
## Logging Configuration
#logging:
#  level:
#    es.in2.wallet.crypto.service: DEBUG
#
#wallet-data:
#  url: http://localhost:8086/api/dids
#
#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: health, info, loggers, metrics
#      base-path: /
#      path-mapping:
#        health: health
#        info: info
#        loggers: loggers
#        metrics: metrics
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
#    loggers:
#      enabled: true
#    metrics:
#      enabled: true
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /spring-ui
#    tags-sorter: alpha
#    operations-sorter: method
#
#openapi:
#  server:
#    url: http://localhost:8081
#    description: Spring Wallet Crypto API
#  info:
#    title: IN2 Wallet Crypto project
#    version: 0.0.1
#    termsOfService: $apiUrl/terms-of-service
#    license:
#      name: MIT License
#      url: https://choosealicense.com/licenses/mit/
#    contact:
#      email: example@in2.es
#      name: IN2
#      url: https://in2.es
#    description: This API exposes endpoints to manage the IN2 Wallet Crypto.