# Spring Configuration
spring:
  application:
    name: Wallet Crypto
  main:
    web-application-type: reactive
  cloud:
    vault:
      host: vault
      port: 8201
      authentication: token
      token:
      scheme: http
      kv:
        enabled: true
    azure:
      keyvault:
        secret:
          endpoint: https://example
      appconfiguration:
        endpoint: https://example

# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.blockchainconnector: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Application Configuration
app:
  secret-provider:
    name:

# Application Configuration
openapi:
  server:
    url: https://localhost:8080
    description: server description
  info:
    title:  application title
    version: X.Y.Z
    description: application description
    termsOfService: https://example.com/terms-of-service
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    contact:
      email: info@example.com
      name: john doe
      url: https://example.com

# Wallet Configuration
wallet-data:
  url: http://wallet-data:8080
