version: '3.8'
services:

  wallet-crypto:
    container_name: wallet-crypto
    image: wallet-crypto:latest
    command:
      - run
    ports:
      - "8081:8080"
    networks:
      - local

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8201:8201"
    volumes:
      - vault_logs:/vault/logs
      - vault_file:/vault/file
      - ./vault/init.sh:/vault/init.sh
      - ./vault/config.json:/vault/config/config.json
    cap_add:
      - IPC_LOCK
    command: /bin/sh /vault/init.sh
    networks:
      - local

  wallet-data:
    container_name: wallet-data
    image: in2kizuna/wallet-data:v1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: "local-docker"
      SERVER_PORT: "8086"
      APP_URL_API: "http://wallet-data:8086"
      APP_URL_ORION-LD-ADAPTER: "http://broker-adapter:8080"
      APP_URL_WALLET-CRYPTO: "http://wallet-crypto:8081"
    command:
      - run
    ports:
      - "8086:8086"
    links:
      - broker-adapter
    networks:
      - local

  broker-adapter:
    container_name: broker-adapter
    image: in2kizuna/broker-adapter:v1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8082:8080"
    volumes:
      - ./wallet-config.yml:/src/main/resources/external-config.yml
    networks:
      - local

  orion-ld:
    container_name: orion-ld
    image: fiware/orion-ld:latest
    command: "-dbhost mongodb -port 1026"
    links:
      - mongodb
    ports:
      - "1026:1026"
    networks:
      - local

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - orion_data:/data/db
      - orion_db_config:/data/configdb
    networks:
      - local

networks:
    local:

volumes:
  orion_data:
  orion_db_config:
  vault_logs:
  vault_file:
