version: '3.8'
services:

#  wallet-crypto:
#    container_name: wallet-crypto
#    image: in2walletcrypto:latest
#    links:
#        - wallet-vault

  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    ports:
      - "8200:8200"
    privileged: true

volumes:
  vault-volume: